name: Staging Docker image to Heroku

on:
  push:
    branches: ['staging']

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAG_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: '--no-cache --build-arg BACKEND_URL=${{ secrets.BACKEND_URL_STAG }}'
          process_type: web
