name: Tests

on:
  push:
    branches-ignore: ['staging', 'main']
  pull_request:
    branches: ['staging', 'main']
  workflow_call:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: CI=true npm test -- --coverage
      - name: Upload test coverage
        uses: codecov/codecov-action@v1